name: Run Vitest, Playwright E2E, Linter, and Type Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Run TypeScript type checks
        run: yarn tsc --noEmit

      - name: Run Vitest tests
        run: yarn test:run

      - name: Install Playwright browsers
        run: yarn playwright install

      - name: Start Vite server
        run: yarn dev &
        env:
          NODE_ENV: test

      - name: Wait for Vite server
        run: npx wait-on http://localhost:5173

      - name: Run Playwright E2E tests
        run: yarn playwright test
